"""Canonical writes and exact observation reads owned by the active transaction."""

from typing import Protocol
from uuid import UUID

from services.domain.canonical import (
    CanonicalBusinessKey,
    CanonicalIdentity,
    CanonicalPromotionEvent,
    CanonicalRevision,
)
from services.domain.observations import PriorObservation, Reobservation


class CanonicalRepository(Protocol):
    def get_revision(self, revision_id: UUID) -> CanonicalRevision: ...
    def current(self, identity_id: UUID) -> CanonicalRevision | None: ...
    def lock_key(self, key_type: str, value: str) -> CanonicalBusinessKey | None: ...
    def next_revision_number(self, identity_id: UUID) -> int: ...
    def activate(self, event: CanonicalPromotionEvent) -> None: ...
    def withdraw(self, event: CanonicalPromotionEvent) -> None: ...
    def promotion_events(
        self, identity_id: UUID
    ) -> tuple[CanonicalPromotionEvent, ...]: ...
    def add_identity(self, identity: CanonicalIdentity) -> None: ...
    def add_revision(self, revision: CanonicalRevision) -> None: ...
    def add_key(self, key: CanonicalBusinessKey) -> None: ...
    def get_key(self, key_type: str, value: str) -> CanonicalBusinessKey | None: ...
    def for_candidate(self, candidate_id: UUID) -> CanonicalRevision | None: ...
    def prior_observations(self) -> tuple[PriorObservation, ...]: ...
    def add_reobservation(self, link: Reobservation) -> None: ...
    def reobservations(self, run_id: UUID) -> tuple[Reobservation, ...]: ...
    def link_dependency(self, dependency_id: UUID, identity_id: UUID) -> None: ...
