"""Aggregate-specific derived evidence repositories; transaction owned by the UoW."""

from typing import Protocol
from uuid import UUID

from services.domain.candidates import CandidateRevision
from services.domain.issues import (
    ClassificationResult,
    DataQualityIssue,
    DependencyRecord,
    DuplicateRelation,
    ReviewItem,
    TransformationEvent,
)


class CandidateRepository(Protocol):
    def add(self, revision: CandidateRevision) -> None: ...
    def get(self, revision_id: UUID) -> CandidateRevision: ...
    def for_run(self, run_id: UUID) -> tuple[CandidateRevision, ...]: ...
    def add_transformation(self, event: TransformationEvent) -> None: ...
    def transformations(self, revision_id: UUID) -> tuple[TransformationEvent, ...]: ...
    def add_issue(self, issue: DataQualityIssue) -> None: ...
    def issues(self, revision_id: UUID) -> tuple[DataQualityIssue, ...]: ...


class ClassificationRepository(Protocol):
    def add(self, result: ClassificationResult) -> None: ...
    def for_revision(self, revision_id: UUID) -> tuple[ClassificationResult, ...]: ...
    def add_dependency(self, dependency: DependencyRecord) -> None: ...
    def dependencies(self, classification_id: UUID) -> tuple[DependencyRecord, ...]: ...
    def add_duplicate(self, duplicate: DuplicateRelation) -> None: ...
    def duplicates(self, later_raw_id: UUID) -> tuple[DuplicateRelation, ...]: ...


class ReviewRepository(Protocol):
    def add(self, review: ReviewItem) -> None: ...
    def for_run(self, run_id: UUID) -> tuple[ReviewItem, ...]: ...
