export const run = {
  id: "11111111-1111-4111-8111-111111111111",
  source_file_id: "source-1",
  state: "staged",
  state_label: "Processed",
  stage_failure: null,
  created_at: {
    instant: "2026-09-16T12:00:00Z",
    display: "16 September 2026, 13:00 BST",
    timezone: "Europe/London",
  },
  counts: {
    CLEAN: 11,
    AUTO_REPAIRED: 2,
    NEEDS_REVIEW: 3,
    REJECTED: 1,
    DUPLICATE: 1,
  },
  filename: "customers-september.csv",
  predecessor_run_id: null,
  reprocess_sequence: 0,
  source_sha256: "abc",
  source_byte_size: 100,
  fx_snapshot_id: null,
  requested_fx_snapshot_date: null,
  rules_version: null,
  build_revision: null,
};
export const secondRun = {
  ...run,
  id: "22222222-2222-4222-8222-222222222222",
  filename: "orders-september.csv",
  state: "classified",
  stage_failure: "load_failed",
  counts: { CLEAN: 2 },
};
export const review = {
  id: "review-1",
  run_id: run.id,
  raw_record_id: "raw-1",
  classification_id: "classification-1",
  candidate_revision_id: "candidate-1",
  entity_type: "PRODUCT",
  verdict: "NEEDS_REVIEW",
  verdict_label: "Needs attention",
  readiness: "ready",
  readiness_label: "Ready",
  effective_state: "pending",
  effective_state_label: "Awaiting review",
  decision_sequence: 0,
  latest_decision_id: null,
  source_line_start: 9,
  source_line_end: 9,
  reason_summaries: ["A number was expected for stock quantity"],
};
export const workspace = {
  scope: { kind: "all", run_ids: [] },
  runs: [run, secondRun],
  review_counts: { pending: 1, approved: 0, rejected: 0, acknowledged: 0 },
};
export const uploaded = {
  source_file_id: "source-1",
  source_occurrence_id: "occurrence-1",
  run_id: run.id,
  source_reused: false,
  run_reused: false,
  duplicate_upload: false,
  resume_from_checkpoint: null,
};
